name: NPM Deploy

on:
  push:
    tags: 
      - v*

env:
  NPM_INSTALL_FLAGS: --force
  PROJECT_ENV: meta
  PROJECT_SERVICE: libraries

jobs:
  deploy:
    name: NPM Deploy
    permissions:
      id-token: write # for aws-actions/configure-aws-credentials
      contents: read # for actions/checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install {{ env.NPM_INSTALL_FLAGS }}
      - name: NPM Deploy
        run: |
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          npm publish --access public
  lint:
    name: Lint (in parallel)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install {{ env.NPM_INSTALL_FLAGS }}
      - run: npm run lint
  test:
    name: Unit Test (in parallel)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install {{ env.NPM_INSTALL_FLAGS }}
    - run: npm test
